f = open(r'C:\Users\spiri\Desktop\подготовка\егэ по информатике\Ромаронио\Умскул\24 Задание класс\Домашка\24.1.txt')
s = f.readline()
s = s.replace('C', 'A')
s = s.split('A')
print(len(max(s, key=len)))